import type {
  CollectionScenario,
  FaqItem,
  Product,
  QuizAnswers,
  QuizRecommendation,
  Testimonial,
} from '@/types/api';
import { zongshenBqh2800Landing } from '@/data/landings/zongshen-bqh-2800-landing';
import { zongshenBqh2200Landing } from '@/data/landings/zongshen-bqh-2200-landing';

export const mockProducts: ReadonlyArray<Product> = [
  {
    id: 'zongshen-bqh-2000',
    name: 'Zongshen BQH 2000',
    brand: 'Zongshen',
    fuel: 'petrol',
    collection: 'country',
    segment: 'home',
    price: 49990,
    power_kw: 1.44,
    phases: 1,
    silence_level: 1,
    badges: ['compact'],
    coverage: ['light', 'wifi'],
    image: '/images/products/product-petrol-compact.jpg',
    short_description: 'Компактный инверторный для дачи: освещение, насос, Wi-Fi.',
    highlights: [
      'Тихий инверторный двигатель Zongshen',
      'Параллельное подключение для удвоения мощности',
      'Вес всего 26 кг',
    ],
    start_type: 'manual',
    enclosure: 'open',
    warranty_years: 2,
  },
  {
    id: 'zongshen-bqh-2200',
    name: 'Zongshen BQH 2200 E',
    brand: 'Zongshen',
    fuel: 'petrol',
    collection: 'country',
    segment: 'home',
    price: 54990,
    power_kw: 1.9,
    phases: 1,
    silence_level: 1,
    badges: ['compact'],
    coverage: ['light', 'cold', 'wifi', 'tv'],
    image: '/images/products/zongshen-bqh-2200.png',
    short_description:
      'BQH 2200 E — ультракомпактный инвертор с электростартом: медь, закрытый кожух, 65 дБ, номинал 1,9 кВт (макс. 2,1 кВт).',
    highlights: [
      'Инвертор — безопасно для смартфонов и ноутбуков',
      'Электростартер при весе 18,3 кг',
      '65 дБ, бак 4 л, расход от 0,36 л/ч',
      'Аккумулятор в комплекте, гарантия 2 года',
    ],
    start_type: 'electric',
    enclosure: 'silent',
    warranty_years: 2,
    landing: zongshenBqh2200Landing,
  },
  {
    id: 'zongshen-bqh-2800',
    name: 'Zongshen BQH 2800 E',
    brand: 'Zongshen',
    fuel: 'petrol',
    collection: 'country',
    segment: 'home',
    price: 59990,
    power_kw: 2.3,
    phases: 1,
    silence_level: 2,
    badges: ['hit', 'compact'],
    coverage: ['light', 'cold', 'tv', 'wifi'],
    image: '/images/products/zongshen-bqh-2800.png',
    short_description:
      'Инверторный генератор BQH 2800 E — компактная станция для дома и отдыха: чистая синусоида для техники, электростарт, закрытый кожух, номинал 2,3 кВт (макс. 2,5 кВт).',
    highlights: [
      'Инверторный «чистый» ток — безопасно для ноутбуков, смартфонов и современных ТВ',
      'Ручной старт и электростартер: запуск без рывка шнура',
      '22 кг, габариты как у дорожной сумки — удобно в багажнике и на балконе',
      'Закрытый кожух IP23, дисплей и счётчик моточасов; бак 5,8 л, выходы 220 В и 12 В (16 А / 8 А)',
      'Двигатель 165FED/P, 149 см³, медная обмотка; масляный датчик и индикатор топлива',
    ],
    start_type: 'electric',
    enclosure: 'silent',
    warranty_years: 2,
    landing: zongshenBqh2800Landing,
  },
  {
    id: 'turnkey-petrol-budget',
    name: 'Решение «под ключ» — бюджет 5 кВт',
    brand: 'Profi',
    fuel: 'turnkey',
    collection: 'country',
    segment: 'home',
    price: 260832,
    power_kw: 5,
    phases: 1,
    silence_level: 2,
    badges: ['turnkey'],
    coverage: ['light', 'cold', 'water', 'wifi'],
    image: '/images/products/product-turnkey-petrol.jpg',
    short_description: 'Минимальный комплект для дачи: 5 кВт + кожух + АВР под ключ.',
    highlights: ['Доступный вход в автоматику', 'Шумозащитный кожух', 'Установка за 1 день'],
    start_type: 'auto',
    enclosure: 'silent',
    warranty_years: 5,
  },
  {
    id: 'zongshen-pb-7000',
    name: 'Zongshen PB 7000',
    brand: 'Zongshen',
    fuel: 'petrol',
    collection: 'comfort',
    segment: 'home',
    price: 70990,
    power_kw: 5.2,
    phases: 1,
    silence_level: 2,
    badges: ['best-value'],
    coverage: ['light', 'cold', 'water', 'tv', 'wifi'],
    image: '/images/products/product-petrol-mid.jpg',
    short_description: 'Универсальный бензиновый генератор для коттеджа на 5 кВт.',
    highlights: ['Счётчик моточасов и AVR', 'Силовая розетка 32 А', 'Бак 27 л'],
    start_type: 'manual',
    enclosure: 'open',
    warranty_years: 2,
  },
  {
    id: 'ctg-cx8500a',
    name: 'CTG CX8500A',
    brand: 'CTG',
    fuel: 'petrol',
    collection: 'comfort',
    segment: 'home',
    price: 72708,
    power_kw: 7.0,
    phases: 1,
    silence_level: 2,
    badges: ['coldproof'],
    coverage: ['light', 'cold', 'water', 'tv', 'wifi', 'kitchen'],
    image: '/images/products/product-petrol-mid.jpg',
    short_description: 'Бензиновый CX8500A 7 кВт с электростартером — комфорт коттеджа.',
    highlights: ['Электростартер LIFAN', 'Защита от перегрузки', 'Колёса в комплекте'],
    start_type: 'electric',
    enclosure: 'open',
    warranty_years: 2,
  },
  {
    id: 'zongshen-kb-6000-e',
    name: 'Zongshen KB 6000 E',
    brand: 'Zongshen',
    fuel: 'petrol',
    collection: 'comfort',
    segment: 'home',
    price: 78990,
    power_kw: 4.4,
    phases: 1,
    silence_level: 2,
    badges: ['hit'],
    coverage: ['light', 'cold', 'water', 'wifi'],
    image: '/images/products/product-petrol-mid.jpg',
    short_description: 'Бензиновый генератор с AVR и электростартером для дома 100 м².',
    highlights: ['Счётчик моточасов и AVR', 'Электростартер + колёса', 'Бак 32 л'],
    start_type: 'electric',
    enclosure: 'open',
    warranty_years: 2,
  },
  {
    id: 'reg-gg10000',
    name: 'REG GG10000',
    brand: 'REG',
    fuel: 'petrol',
    collection: 'comfort',
    segment: 'home',
    price: 97209,
    power_kw: 8.5,
    phases: 1,
    silence_level: 2,
    badges: ['coldproof', 'kristovsky'],
    coverage: ['light', 'cold', 'water', 'tv', 'wifi', 'kitchen', 'ac'],
    image: '/images/products/product-petrol-heavy.jpg',
    short_description: 'REG GG10000 — резерв для дома 200 м², опция АВР для автозапуска.',
    highlights: [
      'Опция автоматического ввода резерва',
      'Воздушное охлаждение',
      'Подходит до 500 м² на газу',
    ],
    start_type: 'electric',
    enclosure: 'open',
    warranty_years: 3,
  },
  {
    id: 'turnkey-petrol-8kw',
    name: 'Решение «под ключ» — бензин 8 кВт',
    brand: 'Profi',
    fuel: 'turnkey',
    collection: 'comfort',
    segment: 'home',
    price: 312000,
    power_kw: 8,
    phases: 1,
    silence_level: 3,
    badges: ['turnkey', 'hit'],
    coverage: ['light', 'cold', 'water', 'tv', 'wifi', 'kitchen', 'heat'],
    image: '/images/products/product-turnkey-petrol.jpg',
    short_description: 'Бензиновый 8 кВт во всепогодном кожухе + АВР под ключ.',
    highlights: ['Шумозащитный кожух', 'АВР: автозапуск без вашего участия', 'Подогрев + пуско-наладка'],
    start_type: 'auto',
    enclosure: 'silent',
    warranty_years: 5,
  },
  {
    id: 'turnkey-gas-8kw',
    name: 'Решение «под ключ» — газ 8 кВт',
    brand: 'Profi',
    fuel: 'turnkey',
    collection: 'comfort',
    segment: 'home',
    price: 324000,
    power_kw: 8,
    phases: 1,
    silence_level: 3,
    badges: ['turnkey', 'silent'],
    coverage: ['light', 'cold', 'water', 'tv', 'wifi', 'kitchen', 'heat'],
    image: '/images/products/product-turnkey-gas.jpg',
    short_description: 'Газовый генератор 8 кВт «под ключ» с АВР: магистраль и газгольдер.',
    highlights: ['Работает от магистрали и баллонов', 'АВР, подогрев, монтаж', 'Самый экономный вид топлива'],
    start_type: 'auto',
    enclosure: 'silent',
    warranty_years: 5,
  },
  {
    id: 'zongshen-bpb-9000-e',
    name: 'Zongshen BPB 9000 E',
    brand: 'Zongshen',
    fuel: 'petrol',
    collection: 'fortress',
    segment: 'home',
    price: 149990,
    power_kw: 6,
    phases: 1,
    silence_level: 2,
    badges: ['hit'],
    coverage: ['light', 'cold', 'water', 'tv', 'wifi', 'kitchen', 'ac', 'heat'],
    image: '/images/products/product-petrol-heavy.jpg',
    short_description: 'Тяжёлый бензиновый 6 кВт с AVR и электростартером.',
    highlights: ['Силовая розетка 32 А', 'Бак 30 л — до 10 ч', 'Электростартер'],
    start_type: 'electric',
    enclosure: 'open',
    warranty_years: 2,
  },
  {
    id: 'ctg-cd20000a',
    name: 'CTG CD20000A',
    brand: 'CTG',
    fuel: 'diesel',
    collection: 'fortress',
    segment: 'home',
    price: 354410,
    power_kw: 14,
    phases: 1,
    silence_level: 2,
    badges: ['coldproof'],
    coverage: ['light', 'cold', 'water', 'tv', 'wifi', 'kitchen', 'ac', 'heat'],
    image: '/images/products/product-diesel-open.jpg',
    short_description: 'Дизельный CD20000A 14 кВт для дома 300+ м² и долгой работы.',
    highlights: ['Дизель — до суток на одной заправке', 'Котёл, сауна, бассейн', 'Колёса для перемещения'],
    start_type: 'electric',
    enclosure: 'open',
    warranty_years: 2,
  },
  {
    id: 'ctg-cg10000sa',
    name: 'CTG CG10000SA Silent',
    brand: 'CTG',
    fuel: 'gas',
    collection: 'fortress',
    segment: 'home',
    price: 560000,
    power_kw: 9.8,
    phases: 1,
    silence_level: 3,
    badges: ['silent', 'kristovsky', 'coldproof'],
    coverage: ['light', 'cold', 'water', 'tv', 'wifi', 'kitchen', 'ac', 'heat'],
    image: '/images/products/product-gas-silent.jpg',
    short_description: 'Газовый 9.8 кВт в премиум шумозащитном кожухе.',
    highlights: ['Шумозащитный кожух — 55 дБ', 'Двигатель Loncin', 'Магистраль + газгольдер'],
    start_type: 'auto',
    enclosure: 'silent',
    warranty_years: 5,
  },
  {
    id: 'turnkey-petrol-10kw',
    name: 'Решение «под ключ» — бензин 10 кВт',
    brand: 'Profi',
    fuel: 'turnkey',
    collection: 'fortress',
    segment: 'home',
    price: 473368,
    power_kw: 10,
    phases: 1,
    silence_level: 3,
    badges: ['turnkey', 'kristovsky'],
    coverage: ['light', 'cold', 'water', 'tv', 'wifi', 'kitchen', 'ac', 'heat'],
    image: '/images/products/product-turnkey-petrol.jpg',
    short_description: 'Полный комплект: бензиновый 10 кВт + кожух + АВР + монтаж.',
    highlights: ['Шумозащитный всепогодный кожух', 'АВР с механической блокировкой', 'До 350 м²'],
    start_type: 'auto',
    enclosure: 'all-weather',
    warranty_years: 7,
  },
  {
    id: 'turnkey-diesel-12kw',
    name: 'Решение «под ключ» — дизель 12 кВт',
    brand: 'Profi',
    fuel: 'turnkey',
    collection: 'fortress',
    segment: 'home',
    price: 509388,
    power_kw: 12,
    phases: 1,
    silence_level: 3,
    badges: ['turnkey', 'coldproof'],
    coverage: ['light', 'cold', 'water', 'tv', 'wifi', 'kitchen', 'ac', 'heat'],
    image: '/images/products/product-turnkey-diesel.jpg',
    short_description: 'Дизельный 12 кВт под ключ — холодный пуск и долгая работа.',
    highlights: ['Зимний пакет с подогревом', 'Бак 60 л — сутки автономии', 'Для крепости 300+ м²'],
    start_type: 'auto',
    enclosure: 'all-weather',
    warranty_years: 7,
  },
  {
    id: 'turnkey-pro-30kw',
    name: 'Решение «под ключ» — Pro 30 кВт',
    brand: 'Profi',
    fuel: 'turnkey',
    collection: 'fortress',
    segment: 'home',
    price: 1004404,
    power_kw: 30,
    phases: 3,
    silence_level: 3,
    badges: ['turnkey', 'silent'],
    coverage: ['light', 'cold', 'water', 'tv', 'wifi', 'kitchen', 'ac', 'heat'],
    image: '/images/products/product-turnkey-pro.jpg',
    short_description: 'Профессиональное решение для крепости 500+ м² и 3 фаз.',
    highlights: ['Трёхфазный 30 кВт', 'Контейнерное исполнение', 'Полный энергоаудит и проект'],
    start_type: 'auto',
    enclosure: 'all-weather',
    warranty_years: 10,
  },
  {
    id: 'retail-gas-15kw',
    name: 'Profi Retail Gas 15 кВт',
    brand: 'Profi',
    fuel: 'gas',
    collection: 'retail',
    segment: 'business',
    price: 745000,
    power_kw: 15,
    phases: 1,
    silence_level: 3,
    badges: ['turnkey', 'silent'],
    coverage: ['pos', 'cold', 'light', 'wifi'],
    image: '/images/products/product-gas-silent.jpg',
    short_description: 'Газовый генератор для магазина и аптеки: тишина, экономия, автозапуск.',
    highlights: ['Защита касс и холодильников', 'Окупаемость от 6 мес.', 'Магистраль/баллоны'],
    start_type: 'auto',
    enclosure: 'silent',
    warranty_years: 7,
  },
  {
    id: 'production-diesel-50kw',
    name: 'Profi Production Diesel 50 кВт',
    brand: 'Profi',
    fuel: 'diesel',
    collection: 'production',
    segment: 'business',
    price: 1850000,
    power_kw: 50,
    phases: 3,
    silence_level: 2,
    badges: ['turnkey', 'coldproof'],
    coverage: ['machine', 'light', 'wifi'],
    image: '/images/products/product-turnkey-pro.jpg',
    short_description: 'Дизельный 50 кВт для производства: защита от перекоса фаз.',
    highlights: ['Контейнер', 'Защита станков', 'Сутки автономии без дозаправки'],
    start_type: 'auto',
    enclosure: 'all-weather',
    warranty_years: 10,
  },
  {
    id: 'datacenter-hybrid-25kw',
    name: 'Profi Hybrid Data 25 кВт',
    brand: 'Profi',
    fuel: 'turnkey',
    collection: 'datacenter',
    segment: 'business',
    price: 1480000,
    power_kw: 25,
    phases: 3,
    silence_level: 3,
    badges: ['turnkey', 'silent'],
    coverage: ['server', 'wifi', 'ac', 'light'],
    image: '/images/products/product-turnkey-diesel.jpg',
    short_description: 'Гибрид ИБП + газовый генератор для дата-центра и офиса.',
    highlights: ['Мгновенный подхват от ИБП', 'Бесшумная стойка', 'Резерв до недели на газгольдере'],
    start_type: 'auto',
    enclosure: 'silent',
    warranty_years: 10,
  },
];

export const mockCollections: ReadonlyArray<CollectionScenario> = [
  { id: 'country', segment: 'home', background: '/images/collections/country.jpg', badge: 'Хит' },
  {
    id: 'comfort',
    segment: 'home',
    background: '/images/collections/comfort.jpg',
    badge: 'Рекомендует Кристовский',
  },
  {
    id: 'fortress',
    segment: 'home',
    background: '/images/collections/fortress.jpg',
    badge: 'Премиум',
  },
  {
    id: 'retail',
    segment: 'business',
    background: '/images/collections/retail.jpg',
    badge: 'Окупаемость 6 мес.',
  },
  {
    id: 'production',
    segment: 'business',
    background: '/images/collections/production.jpg',
    badge: 'Защита фаз',
  },
  {
    id: 'datacenter',
    segment: 'business',
    background: '/images/collections/datacenter.jpg',
    badge: 'Zero downtime',
  },
];

export const mockTestimonials: ReadonlyArray<Testimonial> = [
  {
    id: 'kristovsky',
    name: 'Сергей Крестовский',
    role: 'Музыкант группы Uma2rman',
    rating: 5,
    date: '2024-04-01',
    short: 'Надёжный и тихий генератор. Полная комплектация, работает без проблем.',
    text:
      'Я, Сергей Крестовский, музыкант группы «Уматурман». Воспользовался услугами компании и остался доволен. Генератор в полной комплектации: подогрев, кожух, самозапуск — всё есть. Работает тихо, стоит на улице, никому не мешает. Компанию смело рекомендую — работают ответственно и профессионально.',
    audio_url: '/audio/kristovsky.mp3',
    avatar: '/images/avatars/kristovskiy.png',
    featured: true,
  },
  {
    id: 'kalashnikov',
    name: 'Борис Калашников',
    role: 'Домовладелец, посёлок Шишовка',
    rating: 5,
    date: '2024-03-15',
    short: 'Надёжный генератор для дома — работает уже год без проблем.',
    text:
      'У нас часто отключают электричество, а в доме дорогая техника и газовый котёл. Хотелось надёжную автономную систему. Генератор работает уже почти год — всё отлично, никаких проблем. Рекомендовал соседям, они тоже приобрели.',
    audio_url: '/audio/kalashnikov.mp3',
    avatar: '/images/avatars/avatar-kalashnikov.jpg',
    featured: false,
  },
  {
    id: 'evgeny',
    name: 'Евгений',
    role: 'Владелец двух домов',
    rating: 5,
    date: '2024-02-20',
    short: 'Отличное сочетание цены и качества — генератор оправдал ожидания.',
    text:
      'Узнал о компании через рекламу и решил приобрести генератор, мне нужен был именно газовый вариант. После покупки остались только положительные впечатления. Рекомендую всем владельцам частных домов!',
    audio_url: '/audio/evgeny.mp3',
    avatar: '/images/avatars/avatar-evgeny.jpg',
    featured: false,
  },
];

export const mockFaq: ReadonlyArray<FaqItem> = [
  {
    id: 'why-not-hypermarket',
    question: 'Почему я не могу просто купить генератор в гипермаркете и вызвать электрика?',
    answer:
      'Купить «коробку» можно везде. Но генератор — сердце домашней энергосистемы. Мы проектируем систему автозапуска и берём ответственность за то, чтобы котёл не сгорел от скачка напряжения.',
  },
  {
    id: 'where-install',
    question: 'Где лучше устанавливать оборудование?',
    answer:
      'В помещении — открытый корпус, металлическая рама, приточно-вытяжная вентиляция и отвод выхлопа. На улице — премиальный шумозащитный кожух с подогревом. Цвет можно выбрать по таблице RAL.',
  },
  {
    id: 'what-if-broken',
    question: 'Что делать, если что-то сломается?',
    answer:
      'Проверьте уровень топлива и масла, оцените состояние аккумулятора, перезапустите. Если не помогло — обратитесь в нашу сервисную службу: гарантийный и постгарантийный ремонт.',
  },
  {
    id: 'three-phase',
    question: 'У меня 3 фазы в доме. Мне нужен трёхфазный генератор?',
    answer:
      'В 90% случаев — нет. Однофазный генератор со специальной схемой коммутации фаз избавляет от перекоса фаз и поломки оборудования.',
  },
  {
    id: 'install-time',
    question: 'Как быстро установят оборудование?',
    answer:
      'В среднем 1–3 дня. Сложные объекты — до недели. Все сроки согласуем заранее.',
  },
  {
    id: 'noise-level',
    question: 'Какой уровень шума у генераторов?',
    answer:
      'Открытые: 75–95 дБ. В шумозащитном кожухе: 55–70 дБ. Дополнительно — виброопоры и глушители.',
  },
  {
    id: 'start-types',
    question: 'Как запускать генератор?',
    answer:
      'Ручной запуск, электростартер, АВР. АВР — золотой стандарт: 10 секунд без вас.',
  },
  {
    id: 'ups-vs-generator',
    question: 'Что лучше: ИБП или генератор?',
    answer:
      'ИБП — мгновенное переключение и тишина, но хватит на часы. Генератор — сутками. Гибрид Profi подхватывает мгновенно и заводится при долгом отключении.',
  },
];

const calculateRecommendations = (answers: QuizAnswers): ReadonlyArray<QuizRecommendation> => {
  const basePower =
    answers.load === 'minimum' ? 5 : answers.load === 'comfort' ? 10 : 16;

  const fuel: QuizRecommendation['fuel'] =
    answers.gas === 'mainline' || answers.gas === 'tank'
      ? 'gas'
      : answers.object === 'industry' || answers.object === 'business'
        ? 'diesel'
        : 'petrol';

  const enclosure: QuizRecommendation['enclosure'] =
    answers.neighbours === 'dense'
      ? 'silent'
      : answers.neighbours === 'industrial'
        ? 'open'
        : 'all-weather';

  const startType: QuizRecommendation['start_type'] =
    answers.start === 'auto' || answers.start === 'remote' ? 'auto' : 'electric';

  const multiplier = enclosure === 'silent' ? 1.25 : 1;
  const basePrice = basePower * 30_000;

  return [
    {
      id: 'config-economy',
      title: 'Эконом-конфигурация',
      fuel,
      power_kw: basePower - 1.5,
      enclosure,
      start_type: startType,
      total_price: Math.round(basePrice * 0.85 * multiplier),
      highlights: [
        'Минимальный набор для запуска без вашего участия',
        'Шумозащитный кожух',
        'Гарантия 5 лет',
      ],
    },
    {
      id: 'config-balanced',
      title: 'Оптимальная конфигурация',
      fuel,
      power_kw: basePower,
      enclosure,
      start_type: startType,
      total_price: Math.round(basePrice * multiplier),
      highlights: [
        'Оптимальный баланс мощности и цены',
        'АВР с двойной блокировкой',
        'Подогрев для зимнего пуска',
        'Установка за 1 день',
      ],
    },
    {
      id: 'config-premium',
      title: 'Премиум-конфигурация',
      fuel,
      power_kw: basePower + 4,
      enclosure,
      start_type: 'auto',
      total_price: Math.round(basePrice * 1.4 * multiplier),
      highlights: [
        'Запас по мощности 30%',
        'Премиум-кожух 55 дБ',
        'Расширенная гарантия 10 лет',
        'Управление через мобильное приложение',
      ],
    },
  ];
};

export const mockRecommend = (answers: QuizAnswers): ReadonlyArray<QuizRecommendation> =>
  calculateRecommendations(answers);
